codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default:
        target: auto
        threshold: 2%

comment:
  require_changes: true
  layout: 'condensed_header, condensed_files, condensed_footer'
  hide_project_coverage: true
