name: 💡 Feature Request
description: Suggest a new feature/enhancement for this project.
title: "[Feature]: "
labels: ['enhancement']

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/teociaps/github-bubble-chart/blob/main/CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Contributing Guidelines.
          required: true

  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Please check existing issues to avoid making duplicates. Any duplicate issue will be closed immediately.
      placeholder: Describe the feature you would like to see added.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the problem(s) your idea will solve.
      placeholder: Is your feature request related to a problem?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other useful information about the idea here.
      placeholder: Provide any additional helpful information.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true