name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'Production'
        type: choice
        options:
          - Production
          - Preview
      tag:
        description: 'Tag for the release. Will be used in production deployments, and ignored for preview.'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Tag Release (Production Only)
        if: ${{ github.event.inputs.environment == 'Production' }}
        run: |
          TAG=${{ github.event.inputs.tag }}

          # Check if the tag already exists
          if git tag -l "v$TAG" | grep -q "v$TAG"; then
            echo "Error: Tag v$TAG already exists."
            exit 1
          fi

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag v$TAG
          git push origin --tags

      - name: Deploy to Vercel Production
        if: ${{ github.event.inputs.environment == 'Production' }}
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

      - name: Deploy to Vercel Preview
        if: ${{ github.event.inputs.environment == 'Preview' }}
        run: |
          echo "Tag provided (ignored for preview): ${{ github.event.inputs.tag }}"
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
