name: Update Language Mappings

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly updates
  workflow_dispatch: # Manual trigger

jobs:
  update-mappings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Update Script
        run: yarn update-langs

      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain languageMappings.json)" ]]; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add languageMappings.json
          git commit -m "Update language mappings [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
